baseURL = "http://projectest02.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "TheBoner"
title = "The Boner"
[markup.goldmark.renderer]
unsafe = true
